---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)

library(plotly)
library(p8105.datasets)
```


Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r}
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)

instacart %>% 
  count(department) %>% 
  filter(n > 5000) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly( y = ~n, color = ~department, 
           type = "bar", colors = "viridis")
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  filter(aisle %in% c("baking ingredients",  "packaged vegetables fruits")) %>%
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  arrange(desc(n)) %>%
  filter(n > 300) %>% 
  plot_ly(x = ~product_name, y = ~n, color = ~aisle, type = "scatter",
          mode= "markers", colors = "viridis")
```

### Chart C

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x = ~aisle, y = ~n, type = "histogram2d", 
    alpha = 0.5
  )
```




